# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import rango.models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20171109_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='filePath',
            field=models.FileField(default=' ', upload_to=rango.models.content_file_name),
            preserve_default=False,
        ),
    ]
